### ISSUE TITLE
Google Credential key commited to repository

### ISSUE THREAD

**Issue by chlif** [KierratyskeskusProject/kierratyskeskus-app#31]
There's a google credential key at `/server/config/keys/googleKey.json`.

To fix this:
1. Remove the key from repository
1. Add `/server/config/keys/googleKey.json` to `.gitignore`
1. Disable and renew the key that is stored in the repository at [Google Cloud](https://cloud.google.com)

**Comment by IO89** [comment]
It is done, key is deleted and we asked person to  create new key in Google cloud platform
